// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(MonedasContext))]
    [Migration("20241111234436_migracionInicial")]
    partial class migracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Data.entidades.CurrencyConversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConvertibilityIndex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Legend")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("currencyConversions");
                });

            modelBuilder.Entity("Data.entidades.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxConversions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxConversions = 10,
                            Name = "Free"
                        },
                        new
                        {
                            Id = 2,
                            MaxConversions = 100,
                            Name = "Trial"
                        },
                        new
                        {
                            Id = 3,
                            MaxConversions = 2147483647,
                            Name = "Pro"
                        });
                });

            modelBuilder.Entity("Data.entidades.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Email = "mauri@example.com",
                            IsActive = true,
                            Password = "mauri",
                            SubscriptionId = 1,
                            Username = "mauri"
                        },
                        new
                        {
                            Id = 4,
                            Email = "mauri@example2.com",
                            IsActive = true,
                            Password = "mauri2",
                            SubscriptionId = 2,
                            Username = "mauri2"
                        },
                        new
                        {
                            Id = 5,
                            Email = "mauri@example3.com",
                            IsActive = true,
                            Password = "mauri3",
                            SubscriptionId = 3,
                            Username = "mauri3"
                        });
                });

            modelBuilder.Entity("Data.entidades.CurrencyConversion", b =>
                {
                    b.HasOne("Data.entidades.User", null)
                        .WithMany("Conversions")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Data.entidades.User", b =>
                {
                    b.HasOne("Data.entidades.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Data.entidades.User", b =>
                {
                    b.Navigation("Conversions");
                });
#pragma warning restore 612, 618
        }
    }
}
